version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
    # Reload config every 6h to fetch updated certificate if available
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - reverse_proxy_net

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/letsencrypt:/etc/letsencrypt:rw
    # Renew certificates every 12h
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # command: certonly --webroot --webroot-path=/var/www/certbot --email real.amacati@gmail.com --agree-tos --no-eff-email --force-renewal -d amacati.me

  ddclient:
    image: lscr.io/linuxserver/ddclient:3.10.0
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./ddclient/config:/config
    restart: unless-stopped


networks:
  reverse_proxy_net:
    external: True
    name: reverse_proxy