global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - 127.0.0.1:9090
  - job_name: training_node
    scrape_interval: 10s
    static_configs:
      - targets:
        - training_node:8080
  - job_name: telemetry_node
    scrape_interval: 10s
    static_configs:
      - targets:
        - telemetry_node:8080
