name: FormatCheck
on:
  push:
    branches:
      - master

jobs:
  FormatCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Checkout code base
      - name: Checkout code
        uses: ./.github/actions/pycodestyle